version: '3.8'

# Example: Connect to existing WireGuard container
# Use this if you already have a running WireGuard container

services:
  # IptablesUI connecting to existing WireGuard container
  iptablesui:
    image: ghcr.io/unlink/iptablesui:latest
    container_name: iptablesui
    network_mode: "container:your-existing-wireguard-container"  # Replace with actual container name
    cap_add:
      - NET_ADMIN  # Required for iptables and wg commands
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=change_me_please
      - SECRET_KEY=your-secret-key-here
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped

# To use this:
# 1. Replace "your-existing-wireguard-container" with your actual WireGuard container name
# 2. Make sure your WireGuard container exposes port 8080 or add it:
#    docker run ... -p 8080:8080 ... your-wireguard-image
# 3. Run: docker-compose -f docker-compose.existing-wg.yml up -d