version: '3.8'

# Standalone IptablesUI (without WireGuard integration)
# Use this if you want to manage iptables on the host system

services:
  iptablesui:
    image: ghcr.io/unlink/iptablesui:latest
    # build: .  # Uncomment to build locally instead
    container_name: iptablesui
    ports:
      - "8080:8080"
    privileged: true  # Required for iptables access on host
    # Alternative to privileged (more secure):
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW  
    network_mode: host  # Access host's network stack
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=change_me_please
      - SECRET_KEY=your-secret-key-here
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data  # Persist rules.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s